//! DELETE THIS FILE ONCE WE GET CONNECTED TO .NET SERVER

export const mockData: Record<string, any> = {
  getLogIn:
    '<results><permissions><window_name>Token</window_name><permission>Token</permission><special_data>848f067f26e4cccf4ada09f5f9cf6014</special_data></permissions></results>',
  getUserPermissions: [
    {
      permission: '',
      special_data: '',
      window_name: 'Default Roster Location',
    },
    {
      permission: 'Advisor',
      special_data: '',
      window_name: 'ProductName',
    },
    {
      permission: 'Ash',
      special_data: 'ash',
      window_name: 'Name',
    },
    {
      permission: 'Bloomingdale',
      special_data: '7369',
      window_name: 'LName',
    },
    {
      permission: 'Clear Signatures',
      special_data: '',
      window_name: 'Anywhere Plan',
    },
    {
      permission: 'Delete',
      special_data: '',
      window_name: 'Anywhere Forms',
    },
    {
      permission: 'Delete',
      special_data: '',
      window_name: 'Anywhere Employment',
    },
    {
      permission: 'Delete',
      special_data: '',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'Insert',
      special_data: '',
      window_name: 'Anywhere OOD',
    },
    {
      permission: 'Insert',
      special_data: '',
      window_name: 'Anywhere Forms',
    },
    {
      permission: 'Insert',
      special_data: '',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'Insert Employers',
      special_data: '',
      window_name: 'Anywhere Employment',
    },
    {
      permission: 'Insert Outcomes',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Insert Services',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'N',
      special_data: '',
      window_name: 'SEDocumentTime',
    },
    {
      permission: 'N',
      special_data: '',
      window_name: 'SESupervisorApprove',
    },
    {
      permission: 'N',
      special_data: '',
      window_name: 'SEShowServiceLocations',
    },
    {
      permission: 'P',
      special_data: '',
      window_name: 'SEAddConsumerOnBillable',
    },
    {
      permission: 'Review',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Token',
      special_data: '17d836fc265aec9095ec57fcde99181c',
      window_name: 'Token',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Plan',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Forms',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Workshop',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Case Notes',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Employment',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Scheduling',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Day Services',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Single Entry',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Transportation',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update',
      special_data: '',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'Update Community Integration',
      special_data: '4',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update Employers',
      special_data: '',
      window_name: 'Anywhere Employment',
    },
    {
      permission: 'Update Home Skills',
      special_data: '1',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update Homemaker Personal Care',
      special_data: '7',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update ICF-Medicaid Required',
      special_data: '9',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update New Community Integration',
      special_data: '5',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update New Type',
      special_data: '6',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update Not Home Skills',
      special_data: '3',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update Outcomes',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'Update Picture',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'Update Services',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere OOD',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Plan',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere eMAR',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Forms',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Workshop',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Case Notes',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Employment',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Scheduling',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Day Services',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Single Entry',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Transportation',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Service Activity',
    },
    {
      permission: 'View',
      special_data: '',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'View Attachments',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View General',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View Incident',
      special_data: '7',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'View Internal Investigation',
      special_data: '10',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'View Location Schedule',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View MUI',
      special_data: '3',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'View Notes',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View Relationships',
      special_data: '',
      window_name: 'Anywhere Demographics',
    },
    {
      permission: 'View UI',
      special_data: '6',
      window_name: 'Anywhere Incident Tracking',
    },
    {
      permission: 'Y',
      special_data: '',
      window_name: 'IsAnAdmin',
    },
    {
      permission: 'Y',
      special_data: 'Business Manager',
      window_name: 'Supervisor',
    },
    {
      permission: 'Y',
      special_data: '',
      window_name: 'EnableCaseNotes',
    },
  ],
  getDefaultAnywhereSettingsJSON: [
    {
      OODPermission: 'Anywhere_OOD',
      RequireViewPlan: 'Y',
      adminPermission: null,
      administrator: 'Y',
      allowCallOffRequests: 'Y',
      anyRequireEndTime: 'Y',
      anyUndocumentedServices: 'Y',
      anywhereConsumerFinancesPermission: 'Anywhere_Consumer_Finances',
      anywhereEmploymentPermission: 'Anywhere_Employment',
      anywhereFSSPermission: null,
      anywhereMainPermission: 'Anywhere',
      anywherePlanPermission: 'Anywhere_Plan',
      anywhereResetPasswordPermission: 'Anywhere_Administration',
      anywhereSchedulingPermission: 'Anywhere_Scheduling',
      appendITCause: 'N',
      appendITImmediateAction: 'N',
      appendITPreventionPlan: 'N',
      appendITSummary: 'Y',
      application: 'Advisor',
      automateSimpleBilling: null,
      azureSttApi: 'b008d8aa64ea4a38950ce6bb4449a54d',
      billableTransportation: 'N',
      caseNotesPermission: 'Anywhere_CaseNotes',
      checklist_days_back: '',
      covidPermission: 'COVID_19',
      dayServicesPermission: 'Anywhere_DayServices',
      defaultEmploymentgroup: '',
      defaultEmploymentgroupname: '',
      defaultEmploymentlocation: '',
      defaultEmploymentlocationname: '',
      defaultFormsgroup: '',
      defaultFormsgroupname: '',
      defaultFormslocation: '0',
      defaultFormslocationname: '',
      defaultMoneyManagementLocation: '0',
      defaultMoneyManagementLocationName: '',
      defaultOODLocation: '0',
      defaultOODLocationName: '',
      defaultOutcomesLocation: '0',
      defaultOutcomesLocationName: '',
      defaultTimeEntrygroup: '',
      defaultTimeEntrygroupname: '',
      defaultTimeEntrylocation: '0',
      defaultTimeEntrylocationname: '',
      defaultcontact: '',
      defaultdayservicelocation: '',
      defaultdayservicelocationname: '',
      defaultplangroup: '',
      defaultplangroupname: '',
      defaultplanlocation: '0',
      defaultplanlocationname: '',
      defaultrostergroup: '',
      defaultrostergroupname: '',
      defaultrosterlocation: '',
      defaultrosterlocationname: '',
      defaulttimeclocklocation: 'notDSCertified',
      defaulttimeclocklocationName: '',
      defaultworkshoplocation: '0',
      defaultworkshoplocationname: '',
      emarPermission: 'Anywhere_eMAR',
      formsPermission: 'Anywhere_Forms',
      incidentTrackingPermission: 'Anywhere_Incident_Tracking',
      incidentTrackingPopulateIncidentDate: 'Y',
      incidentTrackingPopulateIncidentTime: 'Y',
      incidentTrackingPopulateReportedDate: 'Y',
      incidentTrackingPopulateReportedTime: 'Y',
      incidentTrackingShowCauseAndContributingFactors: 'Y',
      incidentTrackingShowPreventionPlan: 'Y',
      incidentTracking_days_back: '365',
      intellivuePermission: 'Anywhere_Intellivue',
      isASupervisor: 'Ash',
      minutesToTimeout: '15',
      notes_days_back: '',
      ohioEVVChangeDate: '2024-07-01',
      oneSpan: '',
      outcomesPermission: 'Anywhere_Outcomes',
      planFormCarryover: null,
      planPeopleId: '9600',
      portraitPath: '\\endor\\wwwroot\\ADVUnit\\Anywhere\\webroot\\images\\portraits\\',
      removeGoalsWidget: 'N',
      removeSEAdminMap: 'N',
      reportSeconds: '15',
      requestOpenShifts: 'Y',
      requireTimeEntryTransportationTimes: 'Y',
      resetPassword: null,
      schedulingPermission: 'Scheduling',
      seShowConsumerNote: 'Y',
      seShowConsumerSignature: 'Y',
      seShowTransportation: 'Y',
      sendWaitingListEmail: null,
      setting_value: '',
      showConsumerNote: null,
      showConsumerSignature: null,
      singleEntryApproveEnabled: 'N',
      singleEntryLocationRequired: '',
      singleEntryPermission: 'Anywhere_SingleEntry',
      stateAbbreviation: 'OH',
      sttEnabled: '',
      transportationPermission: 'Anywhere_Transportation',
      useAbsentFeature: 'Y',
      useProgressNotes: 'Y',
      warningEndTime: null,
      warningStartTime: null,
      webPermission: '',
      workshopPermission: 'Anywhere_Workshop',
    },
  ],
};
